savedir: "hparam_results"
data:
  ntrain: 6480
  nval: 50000
  outcome: consumption_per_capita_per_day
  weight: hh_wgt
  gan: 
    generatorpath: pickled/generator-maxepochs=7500_lr=0.001_batchsize=128_dropout=0.0_trial=0.pickle
    datawrapperpath: pickled/datawrapper-maxepochs=7500_lr=0.001_batchsize=128_dropout=0.0_trial=0.pickle
continuous_gap:
  neural_network:
    n_layers: [1, 2, 3, 4]
    n_hidden_units: [32, 64, 128, 256]
    lr: [0.001, 0.005, 0.01]

