data:
  ntrain: 6480
  nval: 50000
  gan: 
    generatorpath: pickled/generator-maxepochs=5000_lr=0.001_batchsize=256_dropout=0.0.pickle
    datawrapperpath: pickled/datawrapper-maxepochs=5000_lr=0.001_batchsize=256_dropout=0.0.pickle
 #gt:
  #  trainpath: data/train.parquet
rate:
  density_estimation:
    n_features: [0, 1, 2, 4, 8, 16, 32, 50]
    n_bins: [20, 50, 200, 500, 1000, 2000]
    n_knots: [2, 4, 8, 10, 12]
    degree: [2, 3, 4, 5]
continuous_gap:
  neural_network:
    num_layers: [1, 2, 3, 4, 5]
    num_hidden_units: [32, 64, 128, 256]
    lr: [0.001, 0.01, 0.1]
  num_quantiles: [5, 10, 20, 30]
binary_gap:
  neural_network:
    num_layers: [1, 2, 3, 4, 5]
    num_hidden_units: [32, 64, 128, 256]
    lr: [0.001, 0.01, 0.1]
  num_quantiles: [5, 10, 20, 30]
rank_order_binary_targeting:
  neural_network:
    num_layers: [1, 2, 3, 4, 5]
    num_hidden_units: [32, 64, 128, 256]
    lr: [0.001, 0.01, 0.1]


