import dill
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F


def generate_synthetic_data(
    generator, data_wrapper, categorical_mapping, nsamples, seed
):
    """
    Generate synthetic data using a trained WGAN generator.

    Args:
        generator (wgan.Generator): Trained WGAN generator.
        data_wrapper (wgan.DataWrapper): DataWrapper object for WGAN training.
        categorical_mapping (list): List of dictionaries containing mappings for categorical variables.
        nsamples (int): Number of samples to generate.
        seed (int): Random seed for synthetic data generation.

    Returns:
        synthetic_df (pd.DataFrame): Synthetic data generated by the WGAN generator.
    """
    rng = np.random.default_rng(seed)
    rand_ints = rng.normal(0, 2**20, nsamples)
    synthetic_df = apply_generator(
        data_wrapper, generator, pd.DataFrame(rand_ints), seed=seed
    )
    vars = (
        data_wrapper.variables["continuous"]
        + data_wrapper.variables["context"]
        + data_wrapper.variables["categorical"]
    )
    synthetic_df.drop(columns=[0], inplace=True)
    # for feature in vars:
    #     if feature.startswith("log_"):
    #         new_feature_name = feature[4:]
    #         synthetic_df[new_feature_name] = np.exp(synthetic_df[feature])
    #         synthetic_df.drop(columns=[feature], inplace=True)
    for col in categorical_mapping:
        synthetic_df[col] = synthetic_df[col].map(categorical_mapping[col])
    return synthetic_df


def convert_to_onehot(df, summary):
    """
    Convert categorical columns to one-hot encoding.

    :param df: The input data.
    :type df: pandas.DataFrame
    :return new_df: The input data with one-hot encoding.
    :rtype: pandas.DataFrame
    """
    categorical_columns = summary[summary["type"] == "categorical"][
        "covariate"
    ].tolist()
    categorical_columns = summary[summary[data_type] == "categorical"][
        covariate
    ].tolist()
    categorical_columns = [col for col in categorical_columns if col in df.columns]

    if len(categorical_columns) > 0:
        one_hot = pd.get_dummies(df[categorical_columns]).astype(np.float32)
        df.drop(columns=categorical_columns, inplace=True)
        try:
            new_df = pd.concat([df, one_hot], axis=1).astype("float32")
        except:
            combined = pd.concat([df, one_hot], axis=1)
            non_numeric_cols = [col for col in combined.columns if not pd.api.types.is_numeric_dtype(combined[col])]
            print("Non-numeric columns:", non_numeric_cols)
            raise
        return new_df
    else:
        return df


def add_missing_columns(df_synthetic, categorical_mapping):
    """
    Add missing columns to the synthetic data.

    :param df_synthetic: The synthetic data.
    :type df_synthetic: pandas.DataFrame
    :param categorical_mapping: The categorical mapping.
    :type categorical_mapping: dict
    """
    missing_cols = [df_synthetic]
    for col in categorical_mapping:
        for code in categorical_mapping[col]:
            cat = categorical_mapping[col][code]
            if f"{col}_{cat}" not in df_synthetic.columns:
                missing_cols.append(
                    pd.DataFrame({f"{col}_{cat}": np.zeros(len(df_synthetic))})
                )

    # Concatenate with the original dataframe (optional)
    df = pd.concat(missing_cols, axis=1)
    return df


def get_wgan_data_generator(objectspath, summarypath):
    """
    Load a trained WGAN generator and data wrapper from disk and return a data generator function.

    Args:
        objectspath (str): Path to the pickled WGAN generator, data wrapper, and categorical mapping.

    Returns:
        data_generator (function): A function that generates synthetic data using the trained WGAN generator
    """
    with open(objectspath, "rb") as dill_file:
        objects = dill.load(dill_file)
        generator = objects["generator"]
        data_wrapper = objects["data_wrapper"]
        categorical_mapping = objects["categorical_mapping"]

    summary = pd.read_parquet(summarypath)

    small_df = generate_synthetic_data(
        generator, data_wrapper, categorical_mapping, 1, 0
    )
    original_cols = small_df.columns.tolist()

    def data_generator(nsamples, seed):
        df_synthetic = generate_synthetic_data(
            generator, data_wrapper, categorical_mapping, nsamples, seed
        )
        df_synthetic_one_hot = convert_to_onehot(df_synthetic, summary)
        df_synthetic_final = add_missing_columns(
            df_synthetic_one_hot, categorical_mapping
        )
        return df_synthetic_final

    return data_generator, original_cols


def get_gt_data_generator(trainpath, summarypath):
    """
    Load the ground truth training dataset and return a data generator function.

    Args:
        trainpath (str): Path to the ground truth training dataset.

    Returns:
        data_generator (function): A function that generates samples from the ground truth dataset.
    """

    data = pd.read_parquet(trainpath).reset_index(drop=True)
    summary = pd.read_parquet(summarypath)

    # some of this preprocessing code should eventually be deprecated because
    # it should be handled by prior data preprocessing code

    # compute outcome conversion factor
    # a = 340.2 / 430.05  # Malawi CPI in 2017 USD / Malawi CPI in 2019 USD
    # b = 241.98  # Malawi Kwacha to USD exchange rate in 2017
    # adulteq = data["adulteq"]
    # can alternatively implement this as data["num_adults"] + alpha * data["num_children"]
    # where alpha is in (0, 1).
    # conversion_factor = (a / b) * (1 / 365) * (1 / adulteq)
    # data["consumption_per_capita_per_day"] = data["rexpagg"] * conversion_factor

    # we include hh_wgt and consumption_per_capita_per_day so that
    # we can synthetically generate samples from the joint distribution (X, Y, R)
    # durable_verifiable_covariates = list(
    #    pd.read_csv("data/durable_verifiable_covariates.csv")["Covariates"]
    # )

    # data = data[
    #    durable_verifiable_covariates + ["consumption_per_capita_per_day", "hh_wgt"]
    # ]

    original_cols = data.columns.tolist()

    data = convert_to_onehot(data, summary)

    def data_generator(nsamples, seed):
        rng = np.random.default_rng(seed)
        sample_indices = rng.choice(data.index, nsamples, replace=True)
        return data.loc[sample_indices].reset_index(drop=True)

    return data_generator, original_cols


def apply_generator(data_wrapper, generator, df, seed):
    """
    Replaces or inserts columns in DataFrame that are generated by the generator, of
    size equal to the number of rows in the DataFrame that is passed

    Parameters
    ----------
    df: pandas.DataFrame
        Must contain columns listed in self.variables["context"], which the generator
        will be conditioned on. Even without context vars, len(df) is used to infer the
        desired sample size, so you need to supply at least pd.DataFrame(index=range(n))
    generator: wgan_model.Generator
        Trained generator for simulating data
    Returns
    -------
    pandas.DataFrame
        Original DataFrame with columns replaced by generated data where possible.
    """
    # replaces or inserts columns in df with data from generator wherever possible
    generator.to("cpu")
    updated = (
        data_wrapper.variables["continuous"] + data_wrapper.variables["categorical"]
    )
    df = df.drop(updated, axis=1, errors="ignore").reset_index(drop=True).copy()
    df = (
        data_wrapper.df0.sample(len(df), replace=True, random_state=seed)
        .reset_index(drop=True)
        .join(df)
    )
    original_columns = df.columns
    x, context = data_wrapper.preprocess(df)
    x_hat = deterministic_forward(generator, context, seed)
    df_hat = data_wrapper.deprocess(x_hat, context)
    not_updated = [col for col in list(df_hat.columns) if col not in updated]
    df_hat = df_hat.drop(not_updated, axis=1).reset_index(drop=True)
    df = df.drop(updated, axis=1).reset_index(drop=True)
    return df_hat.join(df)[original_columns]


def deterministic_forward(generator, context, seed):
    torch.manual_seed(seed)
    noise = torch.randn(context.size(0), generator.d_noise).to(context.device)
    x = torch.cat([noise, context], -1)
    for layer in generator.layers[:-1]:
        x = generator.dropout(F.relu(layer(x)))
    return generator._transform(generator.layers[-1](x))
