savedir: hparam/results/togo
device: cuda
data:
  ntrain: 6480
  nval: 50000
  ntest: 4574
  outcome: consumption_per_capita_per_day
  weight: hhweight
  gt:
    trainpath: data/togo/train.parquet
    summarypath: data/togo/summary.parquet
continuous_gap:
  n_regressors: [10, 20, 30]
  neural_network:
    n_layers: [1, 2, 3]
    n_hidden_units: [256, 1024, 2048]
    lr: [0.001, 0.005, 0.01]



