[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "opt-targeted-transfers"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.8"
authors = [
  {name = "Roshni Sahoo", email = "rsahoo@stanford.edu"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch",
    "scipy",
    "numpy",
    "statsmodels",
    "tqdm",
    "dill"
]
